export const companiesDatabase = [
    { id: '1', name: 'Philips', origin: 'EU', country: 'Netherlands', category: 'Electronics' },
    { id: '2', name: 'Mondelez International', origin: 'Non-EU', country: 'USA', category: 'Food' },
    { id: '3', name: 'Ferrero', origin: 'EU', country: 'Italy', category: 'Food' },
    { id: '4', name: 'Barilla', origin: 'EU', country: 'Italy', category: 'Food' },
    { id: '5', name: 'The Coca-Cola Company', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
    { id: '6', name: 'Haribo', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '7', name: 'Lindt & Sprüngli', origin: 'EU', country: 'Switzerland', category: 'Food' },
    { id: '8', name: 'Kraft Heinz', origin: 'Non-EU', country: 'USA', category: 'Food' },
    { id: '9', name: 'Lavazza', origin: 'EU', country: 'Italy', category: 'Beverages' },
    { id: '10', name: 'Danone', origin: 'EU', country: 'France', category: 'Food' },
    { id: '11', name: 'Siemens', origin: 'EU', country: 'Germany', category: 'Electronics' },
    { id: '12', name: 'Nestlé', origin: 'EU', country: 'Switzerland', category: 'Food' },
    { id: '13', name: 'Unilever', origin: 'EU', country: 'Netherlands/UK', category: 'Consumer Goods' },
    { id: '14', name: 'L\'Oréal', origin: 'EU', country: 'France', category: 'Cosmetics' },
    { id: '15', name: 'Procter & Gamble', origin: 'Non-EU', country: 'USA', category: 'Consumer Goods' },
    { id: '16', name: 'Johnson & Johnson', origin: 'Non-EU', country: 'USA', category: 'Healthcare' },
    { id: '17', name: 'BMW', origin: 'EU', country: 'Germany', category: 'Automotive' },
    { id: '18', name: 'Volkswagen', origin: 'EU', country: 'Germany', category: 'Automotive' },
    { id: '19', name: 'IKEA', origin: 'EU', country: 'Sweden', category: 'Furniture' },
    { id: '20', name: 'H&M', origin: 'EU', country: 'Sweden', category: 'Fashion' },
    { id: '21', name: 'Fanta', origin: 'Non-EU', country: 'USA', category: 'Beverages', parentCompany: 'The Coca-Cola Company' },
    { id: '22', name: 'Pennsylvania Macaroni Company', origin: 'Non-EU', country: 'USA', category: 'Food' },
    { id: '23', name: 'Pennsylvania Dutchman', origin: 'Non-EU', country: 'USA', category: 'Food' },
    { id: '24', name: 'Penny', origin: 'EU', country: 'Germany', category: 'Retail' },
    { id: '25', name: 'Penny Aromico', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '26', name: 'Penny Avena Cerealien GmbH', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '27', name: 'Penny Best Moments', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '28', name: 'Penny Markt', origin: 'EU', country: 'Germany', category: 'Retail' },
    { id: '29', name: 'Penny Natur Gut', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '30', name: 'Penny Ready', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '31', name: 'Penny Wellness Light', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '32', name: 'Pennygate', origin: 'Non-EU', country: 'Unknown', category: 'Unknown' },
    { id: '33', name: 'Pennyloaf Bakery', origin: 'Non-EU', country: 'Unknown', category: 'Bakery' },
    { id: '34', name: 'Pennysticks', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '35', name: 'Penotti', origin: 'EU', country: 'Netherlands', category: 'Food' },
    { id: '36', name: 'Pensa Bio', origin: 'EU', country: 'Italy', category: 'Food' },
    { id: '37', name: 'Penseé Santé', origin: 'EU', country: 'France', category: 'Healthcare' },
    { id: '38', name: 'Pepsi', origin: 'Non-EU', country: 'USA', category: 'Beverages', parentCompany: 'PepsiCo' },
    { id: '39', name: 'Pepsi Max', origin: 'Non-EU', country: 'USA', category: 'Beverages', parentCompany: 'PepsiCo' },
    { id: '40', name: 'Pepsi Light', origin: 'Non-EU', country: 'USA', category: 'Beverages', parentCompany: 'PepsiCo' },
    { id: '41', name: 'Pepsi Twist', origin: 'Non-EU', country: 'USA', category: 'Beverages', parentCompany: 'PepsiCo' },
    { id: '42', name: 'Pepsi Zero', origin: 'Non-EU', country: 'USA', category: 'Beverages', parentCompany: 'PepsiCo' },
    { id: '43', name: 'PepsiCo', origin: 'Non-EU', country: 'USA', category: 'Consumer Goods' },
    { id: '44', name: 'Pepsodent', origin: 'Non-EU', country: 'USA', category: 'Personal Care', parentCompany: 'Unilever' },
    { id: '45', name: 'Pepto-Bismol', origin: 'Non-EU', country: 'USA', category: 'Healthcare', parentCompany: 'Procter & Gamble' },
    { id: '46', name: 'The Co-operative Bakery', origin: 'EU', country: 'UK', category: 'Bakery' },
    { id: '47', name: 'The Co-operative Food', origin: 'EU', country: 'UK', category: 'Retail' },
    { id: '48', name: 'The Co-operative Loved by Us', origin: 'EU', country: 'UK', category: 'Food' },
    { id: '49', name: 'The Coca-Cola Company', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
    { id: '50', name: 'The Coconut Collab', origin: 'EU', country: 'UK', category: 'Food' },
    { id: '51', name: 'The Coffee Bean & Tea Leaf', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
    { id: '52', name: 'The Collective', origin: 'EU', country: 'UK', category: 'Dairy' },
    { id: '53', name: 'The Complete Cookie', origin: 'Non-EU', country: 'USA', category: 'Food' },
    { id: '54', name: 'The Cookie Dough Café', origin: 'Non-EU', country: 'USA', category: 'Food' },
    { id: '55', name: 'The Country Chef Bakery Co', origin: 'Non-EU', country: 'Australia', category: 'Bakery' },
    { id: '56', name: 'The Cultured Collective', origin: 'EU', country: 'UK', category: 'Food' },
    { id: '46', name: 'The Co-operative Bakery', origin: 'EU', country: 'UK', category: 'Bakery' },
    { id: '47', name: 'The Co-operative Food', origin: 'EU', country: 'UK', category: 'Retail' },
    { id: '48', name: 'The Co-operative Loved by Us', origin: 'EU', country: 'UK', category: 'Food' },
    { id: '49', name: 'The Coca-Cola Company', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
    { id: '50', name: 'The Coconut Collab', origin: 'EU', country: 'UK', category: 'Food' },
    { id: '51', name: 'The Coffee Bean & Tea Leaf', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
    { id: '52', name: 'The Collective', origin: 'EU', country: 'UK', category: 'Dairy' },
    { id: '53', name: 'The Complete Cookie', origin: 'Non-EU', country: 'USA', category: 'Food' },
    { id: '54', name: 'The Cookie Dough Café', origin: 'Non-EU', country: 'USA', category: 'Food' },
    { id: '55', name: 'The Country Chef Bakery Co', origin: 'Non-EU', country: 'Australia', category: 'Bakery' },
    { id: '56', name: 'The Cultured Collective', origin: 'EU', country: 'UK', category: 'Food' },
    { id: '57', name: 'The Dannon Company Inc', origin: 'Non-EU', country: 'USA', category: 'Dairy', parentCompany: 'Danone' },
    { id: '58', name: 'The Danone Group', origin: 'EU', country: 'France', category: 'Dairy' },
    { id: '59', name: 'The Drinks Bakery', origin: 'EU', country: 'UK', category: 'Food' },
    { id: '60', name: 'The Essential Baking Company', origin: 'Non-EU', country: 'USA', category: 'Bakery' },
    { id: '61', name: 'The Famous Grouse', origin: 'EU', country: 'Scotland', category: 'Beverages' },
    { id: '62', name: 'The Fine Cheese Co', origin: 'EU', country: 'UK', category: 'Dairy' },
    { id: '63', name: 'The Fishmonger', origin: 'EU', country: 'UK', category: 'Seafood' },
    { id: '64', name: 'The Food Company', origin: 'EU', country: 'UK', category: 'Food' },
    { id: '46', name: 'The Co-operative Bakery', origin: 'EU', country: 'UK', category: 'Bakery' },
  { id: '47', name: 'The Co-operative Food', origin: 'EU', country: 'UK', category: 'Retail' },
  { id: '48', name: 'The Co-operative Loved by Us', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '49', name: 'The Coca-Cola Company', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '50', name: 'The Coconut Collab', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '51', name: 'The Coffee Bean & Tea Leaf', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '52', name: 'The Collective', origin: 'EU', country: 'UK', category: 'Dairy' },
  { id: '53', name: 'The Complete Cookie', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '54', name: 'The Cookie Dough Café', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '55', name: 'The Country Chef Bakery Co', origin: 'Non-EU', country: 'Australia', category: 'Bakery' },
  { id: '56', name: 'The Cultured Collective', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '57', name: 'The Dannon Company Inc', origin: 'Non-EU', country: 'USA', category: 'Dairy', parentCompany: 'Danone' },
  { id: '58', name: 'The Danone Group', origin: 'EU', country: 'France', category: 'Dairy' },
  { id: '59', name: 'The Drinks Bakery', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '60', name: 'The Essential Baking Company', origin: 'Non-EU', country: 'USA', category: 'Bakery' },
  { id: '61', name: 'The Famous Grouse', origin: 'EU', country: 'Scotland', category: 'Beverages' },
  { id: '62', name: 'The Fine Cheese Co', origin: 'EU', country: 'UK', category: 'Dairy' },
  { id: '63', name: 'The Fishmonger', origin: 'EU', country: 'UK', category: 'Seafood' },
  { id: '64', name: 'The Food Company', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '65', name: 'Alnatura', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '66', name: 'Alnavit', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '67', name: 'Aloe Vera King', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '68', name: 'Alo Drink Canarias', origin: 'EU', country: 'Spain', category: 'Beverages' },
  { id: '69', name: 'Aloe Pura', origin: 'EU', country: 'UK', category: 'Health' },
  { id: '70', name: 'Aloe Vera Drink', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '71', name: 'Aloha', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '72', name: 'Aloha Gourmet Products', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '73', name: 'Aloha Organic Protein Bars', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '74', name: 'Aloha Shoyu Company Ltd', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '75', name: 'Alois Müller', origin: 'EU', country: 'Germany', category: 'Dairy' },
  { id: '76', name: 'Alouette Cheese USA LLC', origin: 'Non-EU', country: 'USA', category: 'Dairy' },
  { id: '71', name: 'Aloha', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '72', name: 'Aloha Gourmet Products', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '73', name: 'Aloha Organic Protein Bars', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '74', name: 'Aloha Shoyu Company Ltd', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '75', name: 'Alois Müller', origin: 'EU', country: 'Germany', category: 'Dairy' },
  { id: '76', name: 'Alouette Cheese USA LLC', origin: 'Non-EU', country: 'USA', category: 'Dairy' },
  { id: '77', name: 'Vermont Creamery', origin: 'Non-EU', country: 'USA', category: 'Dairy' },
  { id: '78', name: 'Vermont Nut Free', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '79', name: 'Vermont Bread Company', origin: 'Non-EU', country: 'USA', category: 'Bakery' },
  { id: '80', name: 'Vermont Coffee Company', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '81', name: 'Vermont Highland Cattle Co', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '82', name: 'Vermondo', origin: 'EU', country: 'Germany', category: 'Food', parentCompany: 'Lidl' },
  { id: '83', name: 'Nestlé', origin: 'EU', country: 'Switzerland', category: 'Food & Beverages' },
  { id: '84', name: 'Nestlé Nescafé', origin: 'EU', country: 'Switzerland', category: 'Beverages', parentCompany: 'Nestlé' },
  { id: '85', name: 'Nestlé Milo', origin: 'EU', country: 'Switzerland', category: 'Beverages', parentCompany: 'Nestlé' },
  { id: '86', name: 'Nestlé KitKat', origin: 'EU', country: 'Switzerland', category: 'Confectionery', parentCompany: 'Nestlé' },
  { id: '87', name: 'Nestlé Nesquik', origin: 'EU', country: 'Switzerland', category: 'Beverages', parentCompany: 'Nestlé' },
  { id: '88', name: 'Nestlé Maggi', origin: 'EU', country: 'Switzerland', category: 'Food', parentCompany: 'Nestlé' },
  { id: '89', name: 'Nestlé Toll House', origin: 'EU', country: 'Switzerland', category: 'Bakery', parentCompany: 'Nestlé' },
  { id: '90', name: 'Nestlé Pure Life', origin: 'EU', country: 'Switzerland', category: 'Beverages', parentCompany: 'Nestlé' },
  { id: '91', name: 'Nestlé Gerber', origin: 'EU', country: 'Switzerland', category: 'Baby Food', parentCompany: 'Nestlé' },
  { id: '92', name: 'Nestlé Carnation', origin: 'EU', country: 'Switzerland', category: 'Dairy', parentCompany: 'Nestlé' },
  { id: '93', name: 'Nestlé Health Science', origin: 'EU', country: 'Switzerland', category: 'Health', parentCompany: 'Nestlé' },
  { id: '94', name: 'Nestlé Haagen-Dazs', origin: 'EU', country: 'Switzerland', category: 'Ice Cream', parentCompany: 'Nestlé' },
  { id: '95', name: 'Nestlé Professional', origin: 'EU', country: 'Switzerland', category: 'Food Service', parentCompany: 'Nestlé' },
  { id: '96', name: 'Nestlé Wagner', origin: 'EU', country: 'Germany', category: 'Frozen Food', parentCompany: 'Nestlé' },
  { id: '97', name: 'Nestlé Smarties', origin: 'EU', country: 'Switzerland', category: 'Confectionery', parentCompany: 'Nestlé' },
  { id: '98', name: 'Nestlé Perugina', origin: 'EU', country: 'Italy', category: 'Confectionery', parentCompany: 'Nestlé' },
  { id: '99', name: 'Nestlé Waters', origin: 'EU', country: 'Switzerland', category: 'Beverages', parentCompany: 'Nestlé' },
  { id: '100', name: 'Nestlé La Laitière', origin: 'EU', country: 'France', category: 'Dairy', parentCompany: 'Nestlé' },
  { id: '101', name: 'Netto Marken-Discount', origin: 'EU', country: 'Germany', category: 'Retail' },
  { id: '102', name: 'Netto Bio', origin: 'EU', country: 'Germany', category: 'Food', parentCompany: 'Netto Marken-Discount' },
  { id: '103', name: 'Netto Marknad Sverige', origin: 'EU', country: 'Sweden', category: 'Retail' },
  { id: '104', name: 'Netto Cafet', origin: 'EU', country: 'Germany', category: 'Food', parentCompany: 'Netto Marken-Discount' },
  { id: '105', name: 'Netherend Farm', origin: 'EU', country: 'UK', category: 'Dairy' },
  { id: '106', name: 'Nestum', origin: 'EU', country: 'Switzerland', category: 'Baby Food', parentCompany: 'Nestlé' },
  { id: '107', name: 'Nestlé Fitness', origin: 'EU', country: 'Switzerland', category: 'Cereal', parentCompany: 'Nestlé' },
  { id: '108', name: 'Netto Gutes Land', origin: 'EU', country: 'Germany', category: 'Food', parentCompany: 'Netto Marken-Discount' },
  { id: '109', name: 'Neuburger Milchwerke GmbH', origin: 'EU', country: 'Germany', category: 'Dairy' },
  { id: '110', name: 'Neudorff', origin: 'EU', country: 'Germany', category: 'Agriculture' },
  { id: '111', name: 'Neufchâtel', origin: 'EU', country: 'France', category: 'Dairy' },
  { id: '112', name: 'Neufeldner Biobrauerei', origin: 'EU', country: 'Austria', category: 'Beverages' },
  { id: '113', name: 'Neuhaus', origin: 'EU', country: 'Belgium', category: 'Confectionery' },
  { id: '114', name: 'Neumarkter Lammsbräu', origin: 'EU', country: 'Germany', category: 'Beverages' },
  { id: '115', name: 'Neutrogena', origin: 'Non-EU', country: 'USA', category: 'Personal Care', parentCompany: 'Johnson & Johnson' },
  { id: '116', name: 'Neutro Roberts', origin: 'EU', country: 'Italy', category: 'Personal Care' },
  { id: '117', name: 'Neuzeller Kloster Bräu', origin: 'EU', country: 'Germany', category: 'Beverages' },
  { id: '118', name: 'New England Coffee', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '119', name: 'New England Confectionery Company', origin: 'Non-EU', country: 'USA', category: 'Confectionery' },
  { id: '120', name: 'New Covent Garden Soup Co', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '121', name: 'New Holland Brewing', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '122', name: 'New Mexico Piñon Coffee', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '123', name: 'New Orleans Ice Cream Co', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '124', name: 'New York Bakery Co', origin: 'EU', country: 'UK', category: 'Bakery' },
  { id: '125', name: 'New York Style', origin: 'Non-EU', country: 'USA', category: 'Snacks' },
  { id: '126', name: 'New Zealand Honey Co', origin: 'Non-EU', country: 'New Zealand', category: 'Food' },
  { id: '127', name: 'New World Pasta Company', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '128', name: 'Newman\'s Own', origin: 'Non-EU', country: 'USA', category: 'Food' },
    { id: '129', name: 'Newman\'s Own Organics', origin: 'Non-EU', country: 'USA', category: 'Food', parentCompany: 'Newman\'s Own' },
    { id: '130', name: 'Nexba', origin: 'Non-EU', country: 'Australia', category: 'Beverages' },
    { id: '131', name: 'Next Level Meat', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '132', name: 'Nexxus', origin: 'Non-EU', country: 'USA', category: 'Personal Care', parentCompany: 'Unilever' },
    { id: '133', name: 'Nezo Salt', origin: 'EU', country: 'Netherlands', category: 'Food' },
    { id: '134', name: 'Niagara Bottling LLC', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
    { id: '135', name: 'Niagara Chocolates', origin: 'Non-EU', country: 'USA', category: 'Confectionery' },
    { id: '136', name: 'Nicks', origin: 'EU', country: 'Sweden', category: 'Food' },
    { id: '137', name: 'Nicolás Alziari', origin: 'EU', country: 'France', category: 'Food' },
    { id: '138', name: 'Nidal', origin: 'EU', country: 'France', category: 'Dairy', parentCompany: 'Nestlé' },
    { id: '139', name: 'Nidar', origin: 'EU', country: 'Norway', category: 'Confectionery', parentCompany: 'Orkla' },
    { id: '140', name: 'Niederegger', origin: 'EU', country: 'Germany', category: 'Confectionery' },
    { id: '141', name: 'Niehoffs Vaihinger', origin: 'EU', country: 'Germany', category: 'Beverages' },
    { id: '142', name: 'Nielsen-Massey Vanillas', origin: 'Non-EU', country: 'USA', category: 'Food' },
    { id: '143', name: 'Niepoort', origin: 'EU', country: 'Portugal', category: 'Beverages' },
    { id: '144', name: 'Night Shift Brewing', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
    { id: '145', name: 'Niharti', origin: 'EU', country: 'UK', category: 'Food' },
    { id: '146', name: 'Niagara Bottling LLC', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
    { id: '147', name: 'Nicks', origin: 'EU', country: 'Sweden', category: 'Food' },
    { id: '148', name: 'Nikka Whisky', origin: 'Non-EU', country: 'Japan', category: 'Beverages' },
    { id: '149', name: 'Nikki’s Coconut Butter LLC', origin: 'Non-EU', country: 'USA', category: 'Food' },
    { id: '150', name: 'Nikkos', origin: 'EU', country: 'Greece', category: 'Dairy' },
    { id: '151', name: 'Niko', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '152', name: 'Nikola’s Bakery', origin: 'EU', country: 'Greece', category: 'Bakery' },
    { id: '153', name: 'Nikolopoulos', origin: 'EU', country: 'Greece', category: 'Food' },
    { id: '154', name: 'Nikos', origin: 'EU', country: 'Greece', category: 'Dairy' },
    { id: '155', name: 'Nikwax', origin: 'EU', country: 'UK', category: 'Personal Care' },
    { id: '156', name: 'Nippon Ham', origin: 'Non-EU', country: 'Japan', category: 'Food' },
    { id: '157', name: 'Nippon Shokken', origin: 'Non-EU', country: 'Japan', category: 'Food' },
    { id: '158', name: 'Nippon Suisan Kaisha Ltd', origin: 'Non-EU', country: 'Japan', category: 'Seafood' },
    { id: '159', name: 'Nissin Foods', origin: 'Non-EU', country: 'Japan', category: 'Food' },
    { id: '160', name: 'Nissin Cup Noodles', origin: 'Non-EU', country: 'Japan', category: 'Food', parentCompany: 'Nissin Foods' },
    { id: '161', name: 'Nivea', origin: 'EU', country: 'Germany', category: 'Personal Care', parentCompany: 'Beiersdorf' },
    { id: '162', name: 'Nivea Men', origin: 'EU', country: 'Germany', category: 'Personal Care', parentCompany: 'Beiersdorf' },
    { id: '163', name: 'Nordic Naturals', origin: 'Non-EU', country: 'USA', category: 'Health' },
    { id: '164', name: 'Nordic Seafood', origin: 'EU', country: 'Denmark', category: 'Seafood' },
    { id: '165', name: 'Nordsee', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '166', name: 'Nordzucker', origin: 'EU', country: 'Germany', category: 'Food' },
    { id: '167', name: 'Norr Organic', origin: 'Non-EU', country: 'USA', category: 'Dairy' },
    { id: '168', name: 'Norwegian Salmon', origin: 'EU', country: 'Norway', category: 'Seafood' },
    { id: '169', name: 'Nothing Naughty', origin: 'Non-EU', country: 'New Zealand', category: 'Health' },
    { id: '170', name: 'NotCo', origin: 'Non-EU', country: 'Chile', category: 'Plant-Based Foods' },
    { id: '171', name: 'NotMilk', origin: 'Non-EU', country: 'Chile', category: 'Plant-Based Foods', parentCompany: 'NotCo' },
    { id: '172', name: 'NotMayo', origin: 'Non-EU', country: 'Chile', category: 'Plant-Based Foods', parentCompany: 'NotCo' },
    { id: '173', name: 'Nougat Chabert et Guillot', origin: 'EU', country: 'France', category: 'Confectionery' },
    { id: '174', name: 'Nougat Soubeyran', origin: 'EU', country: 'France', category: 'Confectionery' },
    { id: '175', name: 'Nougat Passion', origin: 'EU', country: 'France', category: 'Confectionery' },
    { id: '176', name: 'Nouvelle Agriculture', origin: 'EU', country: 'France', category: 'Food' },
    { id: '177', name: 'NutriPlus', origin: 'EU', country: 'France', category: 'Health' },
  { id: '178', name: 'NutriPower', origin: 'EU', country: 'Germany', category: 'Health' },
  { id: '179', name: 'NutriPur', origin: 'Non-EU', country: 'Canada', category: 'Food' },
  { id: '180', name: 'NutriQuick', origin: 'EU', country: 'Netherlands', category: 'Food' },
  { id: '181', name: 'NutriShake', origin: 'EU', country: 'UK', category: 'Beverages' },
  { id: '182', name: 'NutriSystem', origin: 'Non-EU', country: 'USA', category: 'Health' },
  { id: '183', name: 'NutriWell', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '184', name: 'NutriWorks', origin: 'EU', country: 'Finland', category: 'Health' },
  { id: '185', name: 'Nutro', origin: 'Non-EU', country: 'USA', category: 'Pet Food' },
  { id: '186', name: 'Nutrolin', origin: 'EU', country: 'Finland', category: 'Health' },
  { id: '187', name: 'Nutroma', origin: 'EU', country: 'Belgium', category: 'Dairy' },
  { id: '188', name: 'Nuts About Nature', origin: 'EU', country: 'Germany', category: 'Snacks' },
  { id: '189', name: 'Nuts For Cheese', origin: 'Non-EU', country: 'Canada', category: 'Plant-Based Foods' },
  { id: '190', name: 'Nuts To You Nut Butter', origin: 'Non-EU', country: 'Canada', category: 'Food' },
  { id: '191', name: 'NuttZo', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '192', name: 'NutWave', origin: 'EU', country: 'Spain', category: 'Snacks' },
  { id: '193', name: 'NutriBay', origin: 'EU', country: 'Luxembourg', category: 'Health' },
  { id: '194', name: 'Nutriva', origin: 'EU', country: 'Italy', category: 'Health' },
  { id: '195', name: 'NutriVita', origin: 'EU', country: 'France', category: 'Health' },
  { id: '196', name: 'Obsthof Retter', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '197', name: 'Obstland', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '198', name: 'Obvi', origin: 'Non-EU', country: 'USA', category: 'Health' },
  { id: '199', name: 'Ocado', origin: 'EU', country: 'UK', category: 'Retail' },
  { id: '200', name: 'Ocean Spray', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '201', name: 'Ocean’s Best', origin: 'Non-EU', country: 'Canada', category: 'Seafood' },
  { id: '202', name: 'Ocean Wise', origin: 'Non-EU', country: 'Canada', category: 'Sustainability' },
  { id: '203', name: 'Ocean 52', origin: 'EU', country: 'Spain', category: 'Beverages' },
  { id: '204', name: 'Odell Brewing Co', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '205', name: 'Odense Marcipan', origin: 'EU', country: 'Denmark', category: 'Confectionery' },
  { id: '206', name: 'OeTTINGER', origin: 'EU', country: 'Germany', category: 'Beverages' },
  { id: '207', name: 'Oetker', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '208', name: 'Odysea', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '209', name: 'Oh Henry!', origin: 'Non-EU', country: 'Canada', category: 'Confectionery', parentCompany: 'Hershey' },
  { id: '210', name: 'Oh My Goodness', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '211', name: 'Oh My Oats', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '212', name: 'Ohso Chocolate', origin: 'EU', country: 'UK', category: 'Confectionery' },
  { id: '213', name: 'Oh My Snacks', origin: 'Non-EU', country: 'USA', category: 'Snacks' },
  { id: '214', name: 'Oh My Veg', origin: 'EU', country: 'France', category: 'Vegetarian' },
  { id: '215', name: 'Oh Nuts', origin: 'Non-EU', country: 'USA', category: 'Snacks' },
  { id: '216', name: 'Oh Yeah!', origin: 'Non-EU', country: 'USA', category: 'Nutrition' },
  { id: '217', name: 'Oishi', origin: 'Non-EU', country: 'Philippines', category: 'Snacks' },
  { id: '218', name: 'Oikos', origin: 'Non-EU', country: 'USA', category: 'Dairy', parentCompany: 'Danone' },
  { id: '219', name: 'Olio', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '220', name: 'Oatly', origin: 'EU', country: 'Sweden', category: 'Beverages' },
  { id: '221', name: 'Oetker', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '196', name: 'Obsthof Retter', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '197', name: 'Obstland', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '198', name: 'Obvi', origin: 'Non-EU', country: 'USA', category: 'Health' },
  { id: '199', name: 'Ocado', origin: 'EU', country: 'UK', category: 'Retail' },
  { id: '200', name: 'Ocean Spray', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '201', name: 'Ocean’s Best', origin: 'Non-EU', country: 'Canada', category: 'Seafood' },
  { id: '202', name: 'Ocean Wise', origin: 'Non-EU', country: 'Canada', category: 'Sustainability' },
  { id: '203', name: 'Ocean 52', origin: 'EU', country: 'Spain', category: 'Beverages' },
  { id: '204', name: 'Odell Brewing Co', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '205', name: 'Odense Marcipan', origin: 'EU', country: 'Denmark', category: 'Confectionery' },
  { id: '206', name: 'OeTTINGER', origin: 'EU', country: 'Germany', category: 'Beverages' },
  { id: '207', name: 'Oetker', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '208', name: 'Odysea', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '209', name: 'Oh Henry!', origin: 'Non-EU', country: 'Canada', category: 'Confectionery', parentCompany: 'Hershey' },
  { id: '210', name: 'Oh My Goodness', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '211', name: 'Oh My Oats', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '212', name: 'Ohso Chocolate', origin: 'EU', country: 'UK', category: 'Confectionery' },
  { id: '213', name: 'Oh My Snacks', origin: 'Non-EU', country: 'USA', category: 'Snacks' },
  { id: '214', name: 'Oh My Veg', origin: 'EU', country: 'France', category: 'Vegetarian' },
  { id: '215', name: 'Oh Nuts', origin: 'Non-EU', country: 'USA', category: 'Snacks' },
  { id: '216', name: 'Oh Yeah!', origin: 'Non-EU', country: 'USA', category: 'Nutrition' },
  { id: '217', name: 'Oishi', origin: 'Non-EU', country: 'Philippines', category: 'Snacks' },
  { id: '218', name: 'Oikos', origin: 'Non-EU', country: 'USA', category: 'Dairy', parentCompany: 'Danone' },
  { id: '219', name: 'Olio', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '220', name: 'Oatly', origin: 'EU', country: 'Sweden', category: 'Beverages' },
  { id: '221', name: 'Oetker', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '222', name: 'Old Amsterdam', origin: 'EU', country: 'Netherlands', category: 'Dairy' },
  { id: '223', name: 'Old El Paso', origin: 'Non-EU', country: 'USA', category: 'Food', parentCompany: 'General Mills' },
  { id: '224', name: 'Old Wisconsin', origin: 'Non-EU', country: 'USA', category: 'Meat' },
  { id: '225', name: 'Old Mill', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '226', name: 'Old Trapper', origin: 'Non-EU', country: 'USA', category: 'Meat' },
  { id: '227', name: 'Old World Provisions', origin: 'Non-EU', country: 'USA', category: 'Meat' },
  { id: '228', name: 'Ole', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '229', name: 'Ole Mexican Foods', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '230', name: 'Olea', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '231', name: 'Oleificio Toscano', origin: 'EU', country: 'Italy', category: 'Food' } ,
  { id: '196', name: 'Obsthof Retter', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '197', name: 'Obstland', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '198', name: 'Obvi', origin: 'Non-EU', country: 'USA', category: 'Health' },
  { id: '199', name: 'Ocado', origin: 'EU', country: 'UK', category: 'Retail' },
  { id: '200', name: 'Ocean Spray', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '201', name: 'Ocean’s Best', origin: 'Non-EU', country: 'Canada', category: 'Seafood' },
  { id: '202', name: 'Ocean Wise', origin: 'Non-EU', country: 'Canada', category: 'Sustainability' },
  { id: '203', name: 'Ocean 52', origin: 'EU', country: 'Spain', category: 'Beverages' },
  { id: '204', name: 'Odell Brewing Co', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '205', name: 'Odense Marcipan', origin: 'EU', country: 'Denmark', category: 'Confectionery' },
  { id: '206', name: 'OeTTINGER', origin: 'EU', country: 'Germany', category: 'Beverages' },
  { id: '207', name: 'Oetker', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '208', name: 'Odysea', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '209', name: 'Oh Henry!', origin: 'Non-EU', country: 'Canada', category: 'Confectionery', parentCompany: 'Hershey' },
  { id: '210', name: 'Oh My Goodness', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '211', name: 'Oh My Oats', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '212', name: 'Ohso Chocolate', origin: 'EU', country: 'UK', category: 'Confectionery' },
  { id: '213', name: 'Oh My Snacks', origin: 'Non-EU', country: 'USA', category: 'Snacks' },
  { id: '214', name: 'Oh My Veg', origin: 'EU', country: 'France', category: 'Vegetarian' },
  { id: '215', name: 'Oh Nuts', origin: 'Non-EU', country: 'USA', category: 'Snacks' },
  { id: '216', name: 'Oh Yeah!', origin: 'Non-EU', country: 'USA', category: 'Nutrition' },
  { id: '217', name: 'Oishi', origin: 'Non-EU', country: 'Philippines', category: 'Snacks' },
  { id: '218', name: 'Oikos', origin: 'Non-EU', country: 'USA', category: 'Dairy', parentCompany: 'Danone' },
  { id: '219', name: 'Olio', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '220', name: 'Oatly', origin: 'EU', country: 'Sweden', category: 'Beverages' },
  { id: '221', name: 'Oetker', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '222', name: 'Old Amsterdam', origin: 'EU', country: 'Netherlands', category: 'Dairy' },
  { id: '223', name: 'Old El Paso', origin: 'Non-EU', country: 'USA', category: 'Food', parentCompany: 'General Mills' },
  { id: '224', name: 'Old Wisconsin', origin: 'Non-EU', country: 'USA', category: 'Meat' },
  { id: '225', name: 'Old Mill', origin: 'EU', country: 'UK', category: 'Food' },
  { id: '226', name: 'Old Trapper', origin: 'Non-EU', country: 'USA', category: 'Meat' },
  { id: '227', name: 'Old World Provisions', origin: 'Non-EU', country: 'USA', category: 'Meat' },
  { id: '228', name: 'Ole', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '229', name: 'Ole Mexican Foods', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '230', name: 'Olea', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '231', name: 'Oleificio Toscano', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '232', name: 'Olimp Nutrition', origin: 'EU', country: 'Poland', category: 'Health' },
  { id: '233', name: 'Olivari', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '234', name: 'Olive Garden', origin: 'Non-EU', country: 'USA', category: 'Restaurant' },
  { id: '235', name: 'Olivos del Sur', origin: 'Non-EU', country: 'Chile', category: 'Food' },
  { id: '238', name: 'Olmuhle Hartmann', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '240', name: 'Olmuhle Schwarzkummel', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '241', name: 'Olyra', origin: 'EU', country: 'Greece', category: 'Food' },
  { id: '242', name: 'Olivar de Segura', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '243', name: 'Olivar del Sur', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '244', name: 'Olivia\'s Organics', origin: 'Non-EU', country: 'USA', category: 'Organic' },
  { id: '246', name: 'Oliveco', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '247', name: 'Olive Oil Company', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '241', name: 'Olyra', origin: 'EU', country: 'Greece', category: 'Food' },
  { id: '242', name: 'Olivar de Segura', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '243', name: 'Olivar del Sur', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '244', name: 'Olivia\'s Organics', origin: 'Non-EU', country: 'USA', category: 'Organic' },
  { id: '245', name: 'Olimp Sport Nutrition', origin: 'EU', country: 'Poland', category: 'Health' },
  { id: '246', name: 'Oliveco', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '247', name: 'Olive Oil Company', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '241', name: 'Olyra', origin: 'EU', country: 'Greece', category: 'Food' },
  { id: '242', name: 'Olivar de Segura', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '243', name: 'Olivar del Sur', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '246', name: 'Oliveco', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '247', name: 'Olive Oil Company', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '248', name: 'Oregon Foods', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '249', name: 'Oregon Fruit Products', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '250', name: 'Oregon Ice Cream', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '251', name: 'Oregon Kombucha', origin: 'Non-EU', country: 'USA', category: 'Beverage' },
  { id: '252', name: 'Oregon Orchard', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '253', name: 'Oreo', origin: 'Non-EU', country: 'USA', category: 'Snacks' },
  { id: '254', name: 'Orgain', origin: 'Non-EU', country: 'USA', category: 'Health' },
  { id: '255', name: 'Organix', origin: 'EU', country: 'UK', category: 'Organic' },
  { id: '237', name: 'Olmuhle Fandler', origin: 'EU', country: 'Austria', category: 'Food' },
  { id: '239', name: 'Olmuhle Moog', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '241', name: 'Olyra', origin: 'EU', country: 'Greece', category: 'Food' },
  { id: '242', name: 'Olivar de Segura', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '243', name: 'Olivar del Sur', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '246', name: 'Oliveco', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '247', name: 'Olive Oil Company', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '248', name: 'Oregon Foods', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '249', name: 'Oregon Fruit Products', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '250', name: 'Oregon Ice Cream', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '251', name: 'Oregon Kombucha', origin: 'Non-EU', country: 'USA', category: 'Beverage' },
  { id: '252', name: 'Oregon Orchard', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '253', name: 'Oreo', origin: 'Non-EU', country: 'USA', category: 'Snacks' },
  { id: '254', name: 'Orgain', origin: 'Non-EU', country: 'USA', category: 'Health' },
  { id: '255', name: 'Organix', origin: 'EU', country: 'UK', category: 'Organic' },
  { id: '256', name: 'Organic Valley', origin: 'Non-EU', country: 'USA', category: 'Organic' },
  { id: '257', name: 'Organic Traditions', origin: 'Non-EU', country: 'Canada', category: 'Organic' },
  { id: '258', name: 'Organic Meadow', origin: 'Non-EU', country: 'Canada', category: 'Organic' },
  { id: '259', name: 'Organic Larder', origin: 'EU', country: 'Denmark', category: 'Organic' },
  { id: '260', name: 'Organic India', origin: 'Non-EU', country: 'India', category: 'Health' },
  { id: '261', name: 'Organic Tattva', origin: 'Non-EU', country: 'India', category: 'Organic' },
  { id: '262', name: 'Organic Prosecco', origin: 'EU', country: 'Italy', category: 'Beverage' },
  { id: '263', name: 'Organic Kitchen', origin: 'EU', country: 'Netherlands', category: 'Organic' },
  { id: '264', name: 'Organic Shop', origin: 'Non-EU', country: 'Russia', category: 'Cosmetics' },
  { id: '265', name: 'Organic Roots', origin: 'Non-EU', country: 'USA', category: 'Organic' },
  { id: '240', name: 'Olmuhle Schwarzkummel', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '241', name: 'Olyra', origin: 'EU', country: 'Greece', category: 'Food' },
  { id: '242', name: 'Olivar de Segura', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '243', name: 'Olivar del Sur', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '246', name: 'Oliveco', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '247', name: 'Olive Oil Company', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '248', name: 'Oregon Foods', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '249', name: 'Oregon Fruit Products', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '250', name: 'Oregon Ice Cream', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '251', name: 'Oregon Kombucha', origin: 'Non-EU', country: 'USA', category: 'Beverage' },
  { id: '252', name: 'Oregon Orchard', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '253', name: 'Oreo', origin: 'Non-EU', country: 'USA', category: 'Snacks' },
  { id: '254', name: 'Orgain', origin: 'Non-EU', country: 'USA', category: 'Health' },
  { id: '255', name: 'Organix', origin: 'EU', country: 'UK', category: 'Organic' },
  { id: '256', name: 'Organic Valley', origin: 'Non-EU', country: 'USA', category: 'Organic' },
  { id: '257', name: 'Organic Traditions', origin: 'Non-EU', country: 'Canada', category: 'Organic' },
  { id: '258', name: 'Organic Meadow', origin: 'Non-EU', country: 'Canada', category: 'Organic' },
  { id: '259', name: 'Organic Larder', origin: 'EU', country: 'Denmark', category: 'Organic' },
  { id: '260', name: 'Organic India', origin: 'Non-EU', country: 'India', category: 'Health' },
  { id: '261', name: 'Organic Tattva', origin: 'Non-EU', country: 'India', category: 'Organic' },
  { id: '262', name: 'Organic Prosecco', origin: 'EU', country: 'Italy', category: 'Beverage' },
  { id: '263', name: 'Organic Kitchen', origin: 'EU', country: 'Netherlands', category: 'Organic' },
  { id: '264', name: 'Organic Shop', origin: 'Non-EU', country: 'Russia', category: 'Cosmetics' },
  { id: '265', name: 'Organic Roots', origin: 'Non-EU', country: 'USA', category: 'Organic' },
  { id: '266', name: 'Organicgirl', origin: 'Non-EU', country: 'USA', category: 'Organic' },
  { id: '267', name: 'Organic Traditions', origin: 'Non-EU', country: 'Canada', category: 'Organic' },
  { id: '268', name: 'Oro del Desierto', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '269', name: 'Oroweat', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '270', name: 'Orkla Foods', origin: 'EU', country: 'Norway', category: 'Food' },
  { id: '271', name: 'Orangina', origin: 'EU', country: 'France', category: 'Beverage' },
  { id: '272', name: 'Ostmann', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '273', name: 'Oatly', origin: 'EU', country: 'Sweden', category: 'Beverage' } ,
  { id: '236', name: 'Olmuhle Solling', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '238', name: 'Olmuhle Hartmann', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '240', name: 'Olmuhle Schwarzkummel', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '241', name: 'Olyra', origin: 'EU', country: 'Greece', category: 'Food' },
  { id: '242', name: 'Olivar de Segura', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '243', name: 'Olivar del Sur', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '244', name: 'Olivia\'s Organics', origin: 'Non-EU', country: 'USA', category: 'Organic' },
  { id: '246', name: 'Oliveco', origin: 'EU', country: 'Italy', category: 'Food' },
  { id: '247', name: 'Olive Oil Company', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '248', name: 'Oregon Foods', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '249', name: 'Oregon Fruit Products', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '250', name: 'Oregon Ice Cream', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '251', name: 'Oregon Kombucha', origin: 'Non-EU', country: 'USA', category: 'Beverage' },
  { id: '252', name: 'Oregon Orchard', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '253', name: 'Oreo', origin: 'Non-EU', country: 'USA', category: 'Snacks' },
  { id: '254', name: 'Orgain', origin: 'Non-EU', country: 'USA', category: 'Health' },
  { id: '255', name: 'Organix', origin: 'EU', country: 'UK', category: 'Organic' },
  { id: '256', name: 'Organic Valley', origin: 'Non-EU', country: 'USA', category: 'Organic' },
  { id: '257', name: 'Organic Traditions', origin: 'Non-EU', country: 'Canada', category: 'Organic' },
  { id: '258', name: 'Organic Meadow', origin: 'Non-EU', country: 'Canada', category: 'Organic' },
  { id: '259', name: 'Organic Larder', origin: 'EU', country: 'Denmark', category: 'Organic' },
  { id: '260', name: 'Organic India', origin: 'Non-EU', country: 'India', category: 'Health' },
  { id: '261', name: 'Organic Tattva', origin: 'Non-EU', country: 'India', category: 'Organic' },
  { id: '262', name: 'Organic Prosecco', origin: 'EU', country: 'Italy', category: 'Beverage' },
  { id: '263', name: 'Organic Kitchen', origin: 'EU', country: 'Netherlands', category: 'Organic' },
  { id: '264', name: 'Organic Shop', origin: 'Non-EU', country: 'Russia', category: 'Cosmetics' },
  { id: '265', name: 'Organic Roots', origin: 'Non-EU', country: 'USA', category: 'Organic' },
  { id: '266', name: 'Organicgirl', origin: 'Non-EU', country: 'USA', category: 'Organic' },
  { id: '267', name: 'Organic Traditions', origin: 'Non-EU', country: 'Canada', category: 'Organic' },
  { id: '268', name: 'Oro del Desierto', origin: 'EU', country: 'Spain', category: 'Food' },
  { id: '269', name: 'Oroweat', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '270', name: 'Orkla Foods', origin: 'EU', country: 'Norway', category: 'Food' },
  { id: '271', name: 'Orangina', origin: 'EU', country: 'France', category: 'Beverage' },
  { id: '272', name: 'Ostmann', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '273', name: 'Oatly', origin: 'EU', country: 'Sweden', category: 'Beverage' },
  { id: '274', name: 'Ozarka', origin: 'Non-EU', country: 'USA', category: 'Beverage' },
  { id: '275', name: 'Pace Foods', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '276', name: 'Pacific Foods', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '277', name: 'Paldo', origin: 'Non-EU', country: 'South Korea', category: 'Food' },
  { id: '278', name: 'Paleo Valley', origin: 'Non-EU', country: 'USA', category: 'Health' },
  { id: '279', name: 'Pampers', origin: 'Non-EU', country: 'USA', category: 'Baby Products' },
  { id: '280', name: 'Papa John\'s', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '281', name: 'Patisserie Valerie', origin: 'EU', country: 'UK', category: 'Bakery' },
  { id: '282', name: 'Peet\'s Coffee', origin: 'Non-EU', country: 'USA', category: 'Beverage' },
  { id: '283', name: 'Peter Kolln', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '284', name: 'Peter Mertes', origin: 'EU', country: 'Germany', category: 'Beverage' },
  { id: '22', name: 'Alnatura', origin: 'EU', country: 'Germany', category: 'Food' },
  { id: '23', name: "Annie's", origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '24', name: 'Casino', origin: 'EU', country: 'France', category: 'Retail' },
  { id: '25', name: 'Cemoi', origin: 'EU', country: 'France', category: 'Food' },
  { id: '27', name: 'Edward and Sons', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '28', name: 'Engine 2', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '29', name: 'Harrys', origin: 'EU', country: 'France', category: 'Food' },
  { id: '30', name: 'Maxwell House', origin: 'Non-EU', country: 'USA', category: 'Beverages' },
  { id: '31', name: 'Lipton', origin: 'EU', country: 'UK', category: 'Beverages' },
  { id: '32', name: 'Kelloggs', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '33', name: 'Kraft, Philadelphia', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '34', name: 'Tesco', origin: 'EU', country: 'UK', category: 'Retail' },
  { id: '35', name: 'Danone', origin: 'EU', country: 'France', category: 'Food' },
  { id: '36', name: 'Lotus Foods', origin: 'Non-EU', country: 'USA', category: 'Food' },
  { id: '37', name: 'Maison du café', origin: 'EU', country: 'France', category: 'Beverages' },
  { id: '38', name: 'Spearmint', origin: 'Unknown', country: 'Unknown', category: 'Food' },
  { id: '39', name: 'Les Crudettes', origin: 'EU', country: 'France', category: 'Food' },
  { id: '40', name: 'Liberté', origin: 'EU', country: 'France', category: 'Dairy' },
  { id: '41', name: 'Gurieli', origin: 'EU', country: 'Georgia', category: 'Beverages' },
  { id: '42', name: 'St Feuillien', origin: 'EU', country: 'Belgium', category: 'Beverages' },
  { id: '43', name: 'Hertog Jan', origin: 'EU', country: 'Netherlands', category: 'Beverages' },
  { id: '44', name: 'Oberti', origin: 'EU', country: 'France', category: 'Food' },
  { id: '45', name: 'Ottiger', origin: 'EU', country: 'Switzerland', category: 'Food' },
  { id: '46', name: 'Baumaux', origin: 'EU', country: 'France', category: 'Agriculture' },
  { id: '47', name: 'La Vie Saine', origin: 'EU', country: 'France', category: 'Organic' },
  { id: '48', name: 'Le Verger des Fruits', origin: 'EU', country: 'France', category: 'Food' },
  { id: "50", "name": "Добрый", "origin": "Non-EU", "country": "Russia", "category": "Beverages" },
  { id: "51", "name": "Сибирский гурман", "origin": "Non-EU", "country": "Russia", "category": "Food" },
  { id: "52", "name": "Смак", "origin": "Non-EU", "country": "Russia", "category": "Food" },
  { id: "53", "name": "טרה", "origin": "Non-EU", "country": "Israel", "category": "Dairy" },
  { id: "54", "name": "Вдохновение", "origin": "Non-EU", "country": "Russia", "category": "Confectionery" },
  { id: "55", "name": "\"The Egyptian Company For Foods \"\"Biscomist\"\"\"", "origin": "Non-EU", "country": "Egypt", "category": "Food" },
  { id: "56", "name": "\"Fruttis\"", "origin": "EU", "country": "Russia", "category": "Dairy" },
  { id: "57", "name": "\"KDV Yashkino\" MChJ", "origin": "Non-EU", "country": "Russia", "category": "Food" },
  { id: "58", "name": "\"POLSKI LEK\" Sp. z o.o.", "origin": "EU", "country": "Poland", "category": "Healthcare" },
  { id: "59", "name": "\"Б.Ю.Александров\"", "origin": "Non-EU", "country": "Russia", "category": "Dairy" },
  { id: "60", "name": "\"Будем знакомы\"", "origin": "Non-EU", "country": "Russia", "category": "Food" },
  { id: "61", "name": "\"ПепсиКо Инк\"", "origin": "Non-EU", "country": "USA", "category": "Beverages" },
  { id: "62", "name": "\"Рокадовские минеральные воды\"", "origin": "Non-EU", "country": "Russia", "category": "Beverages" },
  { id: "63", "name": "\"Россия\" - щедрая душа", "origin": "Non-EU", "country": "Russia", "category": "Confectionery" },
  { id: "64", "name": "\"Россия\" — щедрая душа!", "origin": "Non-EU", "country": "Russia", "category": "Confectionery" },
  { "id": "65", "name": "(Aldi) The Fishmonger", "origin": "EU", "country": "Germany", "category": "Food" },
  { "id": "66", "name": "(Oryza)", "origin": "EU", "country": "Germany", "category": "Food" },
  { "id": "67", "name": "(du Bruit dans la Cuisine)", "origin": "EU", "country": "France", "category": "Retail" },
  { "id": "68", "name": "(sans marque)", "origin": "EU", "country": "France", "category": "Generic/Private Label" },
  { "id": "69", "name": "(주) 사조오양", "origin": "Non-EU", "country": "South Korea", "category": "Food" },
  { "id": "70", "name": "(주)뉴트리케어", "origin": "Non-EU", "country": "South Korea", "category": "Healthcare" },
  { "id": "71", "name": "(주)동원F&B", "origin": "Non-EU", "country": "South Korea", "category": "Food" },
  { "id": "72", "name": "(주)이앤오즈", "origin": "Non-EU", "country": "South Korea", "category": "Food" },
  { "id": "73", "name": ",vipiteno,sterzing,Sterzing-Vipiteno,Cooperativa Latteria Vipiteno,Genossenschaft Milchhof Sterzing", "origin": "EU", "country": "Italy", "category": "Dairy" },
  { "id": "74", "name": "1 A Pharma®", "origin": "EU", "country": "Germany", "category": "Pharmaceuticals" },
  { "id": "75", "name": "1 DE BESTE", "origin": "EU", "country": "Netherlands", "category": "Retail" },
  { "id": "76", "name": "1 De Beste", "origin": "EU", "country": "Netherlands", "category": "Retail" },
  { "id": "77", "name": "1-2-3 Gluten Free", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "78", "name": "100 BON", "origin": "EU", "country": "France", "category": "Fragrances" },
  { "id": "79", "name": "100 Plus", "origin": "Non-EU", "country": "Malaysia", "category": "Beverages", "parentCompany": "F&N, Fraser and Neave" },
  { "id": "80", "name": "100% All Natural LLC", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "81", "name": "100% Artisan Foods", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "82", "name": "100% Dairy-free Sheese", "origin": "EU", "country": "UK", "category": "Dairy Alternatives" },
  { "id": "83", "name": "100% GOLD", "origin": "Non-EU", "country": "South Africa", "category": "Food" },
  { "id": "84", "name": "1000 Springs Mill", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "85", "name": "1001 DELIGHTS", "origin": "EU", "country": "Germany", "category": "Food", "parentCompany": "Lidl" },
  { "id": "86", "name": "1001 Cvet", "origin": "Non-EU", "country": "Serbia", "category": "Tea" },
  { "id": "87", "name": "1001 Organic", "origin": "EU", "country": "Germany", "category": "Food" },
  { "id": "88", "name": "101CAFFE", "origin": "EU", "country": "Italy", "category": "Beverages" },
  { "id": "89", "name": "11er", "origin": "EU", "country": "Austria", "category": "Food" },
  { "id": "90", "name": "11te Generation GmbH", "origin": "EU", "country": "Germany", "category": "Food" },
  { "id": "91", "name": "12 Bones", "origin": "Non-EU", "country": "USA", "category": "Restaurant/Food" },
  { "id": "92", "name": "12 Tides", "origin": "Non-EU", "country": "USA", "category": "Snacks" },
  { "id": "93", "name": "12 Linajes", "origin": "EU", "country": "Spain", "category": "Wine" },
  { "id": "94", "name": "123 Gluten Free", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "95", "name": "13 Foods LLC", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "96", "name": "1336", "origin": "EU", "country": "France", "category": "Tea", "parentCompany": "SCOP TI" },
  { "id": "97", "name": "137 Degrees", "origin": "Non-EU", "country": "Thailand", "category": "Beverages" },
  { "id": "98", "name": "1410, Volfas Engelman", "origin": "EU", "country": "Lithuania", "category": "Beverages" },
  { "id": "99", "name": "15th Ave Food Corp.", "origin": "Non-EU", "country": "USA", "category": "Food Distribution" },
  { "id": "100", "name": "1642 Sodas", "origin": "Non-EU", "country": "Canada", "category": "Beverages" },
  { "id": "101", "name": "1664", "origin": "EU", "country": "France", "category": "Beverages", "parentCompany": "Kronenbourg" },
  { "id": "102", "name": "1670 Marquise De Sablé", "origin": "EU", "country": "France", "category": "Confectionery" },
  { "id": "103", "name": "17 Nutrition", "origin": "Non-EU", "country": "USA", "category": "Health & Supplements" },
  { "id": "104", "name": "18 Rabbits", "origin": "Non-EU", "country": "USA", "category": "Snacks" },
  { "id": "105", "name": "180 Degrees", "origin": "Non-EU", "country": "New Zealand", "category": "Snacks" },
  { "id": "106", "name": "180 Snacks", "origin": "Non-EU", "country": "USA", "category": "Snacks" },
  { "id": "107", "name": "1830 Maison Brémond", "origin": "EU", "country": "France", "category": "Gourmet Food" },
  { "id": "108", "name": "1836 Farms", "origin": "Non-EU", "country": "USA", "category": "Dairy" },
  { "id": "109", "name": "1880", "origin": "EU", "country": "Spain", "category": "Confectionery" },
  { "id": "110", "name": "1883 Maison Routin", "origin": "EU", "country": "France", "category": "Beverages" },
  { "id": "111", "name": "1883 Maison Routin", "origin": "EU", "country": "France", "category": "Beverages" },
  { "id": "112", "name": "1890 Nature & Saveurs", "origin": "EU", "country": "France", "category": "Organic Food" },
  { "id": "113", "name": "1899, Morrisons", "origin": "EU", "country": "UK", "category": "Retail", "parentCompany": "Morrisons" },
  { "id": "114", "name": "18th Ave Pasta Company", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "115", "name": "19 Crimes", "origin": "Non-EU", "country": "Australia", "category": "Wine" },
  { "id": "116", "name": "1903 Mexico Cacao Co", "origin": "Non-EU", "country": "Mexico", "category": "Confectionery" },
  { "id": "117", "name": "1906", "origin": "Non-EU", "country": "USA", "category": "Edibles" },
  { "id": "118", "name": "1919 Michelis", "origin": "EU", "country": "Italy", "category": "Pasta" },
  { "id": "119", "name": "1927 Soda Co.", "origin": "Non-EU", "country": "USA", "category": "Beverages", "parentCompany": "7-Eleven" },
  { "id": "120", "name": "1964", "origin": "EU", "country": "France", "category": "Beverages" },
  { "id": "121", "name": "1973, Viani", "origin": "EU", "country": "Italy", "category": "Gourmet Food" },
  { "id": "122", "name": "1UP Nutrition", "origin": "Non-EU", "country": "USA", "category": "Health & Supplements" },
  { "id": "123", "name": "1st Phorm", "origin": "Non-EU", "country": "USA", "category": "Health & Supplements" },
  { "id": "124", "name": "2 Betties", "origin": "Non-EU", "country": "USA", "category": "Snacks" },
  { "id": "125", "name": "2 Gringo's Chupacabra", "origin": "Non-EU", "country": "USA", "category": "Seasonings" },
  { "id": "126", "name": "2 Sisters' Salsa Company", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "127", "name": "2 Towns Ciderhouse", "origin": "Non-EU", "country": "USA", "category": "Beverages" },
  { "id": "128", "name": "21st Century", "origin": "Non-EU", "country": "USA", "category": "Healthcare" },
  { "id": "129", "name": "22 Days Nutrition", "origin": "Non-EU", "country": "USA", "category": "Health & Supplements" },
  { "id": "130", "name": "226ERS", "origin": "EU", "country": "Spain", "category": "Sports Nutrition" },
  { "id": "131", "name": "24 Carrots Bakery", "origin": "Non-EU", "country": "USA", "category": "Bakery" },
  { "id": "132", "name": "24 Hour Meals", "origin": "EU", "country": "UK", "category": "Food" },
  { "id": "133", "name": "24 Ice", "origin": "EU", "country": "Netherlands", "category": "Beverages" },
  { "id": "134", "name": "24 Mantra Organic", "origin": "Non-EU", "country": "India", "category": "Organic Food" },
  { "id": "135", "name": "28 Black", "origin": "EU", "country": "Germany", "category": "Energy Drinks" },
  { "id": "136", "name": "28 Drinks", "origin": "EU", "country": "Germany", "category": "Beverages" },
  { "id": "137", "name": "2B Wild", "origin": "EU", "country": "France", "category": "Food" },
  { "id": "138", "name": "2BSlim", "origin": "EU", "country": "Netherlands", "category": "Dietary Products" },
  { "id": "139", "name": "2GO", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "140", "name": "2Keep", "origin": "EU", "country": "Belgium", "category": "Food Packaging" },
  { "id": "141", "name": "2Pure Protein", "origin": "EU", "country": "Germany", "category": "Sports Nutrition" },
  { "id": "142", "name": "3 Bears", "origin": "EU", "country": "Germany", "category": "Food" },
  { "id": "143", "name": "3 Corações", "origin": "Non-EU", "country": "Brazil", "category": "Beverages" },
  { "id": "144", "name": "3 Diamants", "origin": "Non-EU", "country": "Canada", "category": "Food" },
  { "id": "145", "name": "3 Fonteinen", "origin": "EU", "country": "Belgium", "category": "Beverages" },
  { "id": "146", "name": "3 Glocken", "origin": "EU", "country": "Germany", "category": "Pasta" },
  { "id": "147", "name": "3 Horses", "origin": "EU", "country": "Netherlands", "category": "Beverages" },
  { "id": "148", "name": "3 Kaveria", "origin": "EU", "country": "Finland", "category": "Ice Cream" },
  { "id": "149", "name": "3 Monts", "origin": "EU", "country": "France", "category": "Beverages", "parentCompany": "Brasserie de Saint-Sylvestre" },
  { "id": "150", "name": "3 Pauly", "origin": "EU", "country": "Germany", "category": "Health & Dietary Food" },
  { "id": "151", "name": "3 Sisters", "origin": "Non-EU", "country": "USA", "category": "Cereal" },
  { "id": "152", "name": "3 Vänner", "origin": "EU", "country": "Sweden", "category": "Ice Cream" },
  { "id": "153", "name": "305 Squeezed", "origin": "Non-EU", "country": "USA", "category": "Beverages" },
  { "id": "154", "name": "310 Nutrition", "origin": "Non-EU", "country": "USA", "category": "Health & Supplements" },
  { "id": "155", "name": "32Gi", "origin": "Non-EU", "country": "South Africa", "category": "Sports Nutrition" },
  { "id": "156", "name": "33 Export", "origin": "Non-EU", "country": "Nigeria", "category": "Beverages" },
  { "id": "157", "name": "34 Degrees", "origin": "Non-EU", "country": "USA", "category": "Crackers" },
  { "id": "158", "name": "356 Whole Foods", "origin": "Non-EU", "country": "USA", "category": "Retail", "parentCompany": "Whole Foods Market" },
  { "id": "159", "name": "360 Nutrition", "origin": "Non-EU", "country": "USA", "category": "Health & Supplements" },
  { "id": "160", "name": "365 Everyday Value", "origin": "Non-EU", "country": "USA", "category": "Retail", "parentCompany": "Whole Foods Market" },
  { "id": "161", "name": "365 Delhaize", "origin": "EU", "country": "Belgium", "category": "Retail", "parentCompany": "Delhaize" },
  { "id": "162", "name": "37th Street Bakery", "origin": "Non-EU", "country": "USA", "category": "Bakery" },
  { "id": "163", "name": "38th Street Snacks", "origin": "Non-EU", "country": "USA", "category": "Snacks" },
  { "id": "164", "name": "3D Energy", "origin": "Non-EU", "country": "USA", "category": "Energy Drinks" },
  { "id": "165", "name": "3M", "origin": "Non-EU", "country": "USA", "category": "Consumer Goods" },
  { "id": "166", "name": "3PAULY", "origin": "EU", "country": "Germany", "category": "Health & Dietary Food" },
  { "id": "167", "name": "3Bears", "origin": "EU", "country": "Germany", "category": "Food" },
  { "id": "168", "name": "3Bit", "origin": "EU", "country": "Germany", "category": "Confectionery", "parentCompany": "Mondelez" },
  { "id": "169", "name": "3C Pharma", "origin": "EU", "country": "France", "category": "Healthcare" },
  { "id": "170", "name": "3Glocken", "origin": "EU", "country": "Germany", "category": "Pasta", "parentCompany": "Newlat" },
  { "id": "171", "name": "3rd Street Chai", "origin": "Non-EU", "country": "USA", "category": "Beverages" },
  { "id": "172", "name": "3W", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "173", "name": "4 Buddies", "origin": "EU", "country": "Germany", "category": "Food" },
  { "id": "174", "name": "4 Earth", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "175", "name": "4 Hectares", "origin": "EU", "country": "France", "category": "Wine" },
  { "id": "176", "name": "4 Madonne", "origin": "EU", "country": "Italy", "category": "Dairy" },
  { "id": "177", "name": "4 Pines", "origin": "Non-EU", "country": "Australia", "category": "Beverages" },
  { "id": "178", "name": "4 Sisters", "origin": "Non-EU", "country": "USA", "category": "Rice" },
  { "id": "179", "name": "4+ Nutrition", "origin": "EU", "country": "Italy", "category": "Sports Nutrition" },
  { "id": "180", "name": "44th Street", "origin": "Non-EU", "country": "Canada", "category": "Food" },
  { "id": "181", "name": "4505 Meats", "origin": "Non-EU", "country": "USA", "category": "Meat Products" },
  { "id": "182", "name": "4700BC", "origin": "Non-EU", "country": "India", "category": "Snacks" },
  { "id": "183", "name": "4BRO", "origin": "EU", "country": "Germany", "category": "Beverages & Snacks" },
  { "id": "184", "name": "4C Foods Corp.", "origin": "Non-EU", "country": "USA", "category": "Food & Beverages" },
  { "id": "185", "name": "4Move", "origin": "EU", "country": "Poland", "category": "Sports Drinks", "parentCompany": "FoodCare" },
  { "id": "186", "name": "4th & Heart", "origin": "Non-EU", "country": "USA", "category": "Ghee & Dairy Alternatives" },
  { "id": "187", "name": "5 GUM", "origin": "Non-EU", "country": "USA", "category": "Confectionery", "parentCompany": "Mars Wrigley" },
  { "id": "188", "name": "5 Star", "origin": "Non-EU", "country": "India", "category": "Confectionery", "parentCompany": "Cadbury" },
  { "id": "189", "name": "5% Nutrition", "origin": "Non-EU", "country": "USA", "category": "Sports Nutrition" },
  { "id": "190", "name": "505 Southwestern", "origin": "Non-EU", "country": "USA", "category": "Food" },
  { "id": "191", "name": "51 Fifty Energy", "origin": "Non-EU", "country": "USA", "category": "Energy Drinks" },
  { "id": "192", "name": "555 Tuna", "origin": "Non-EU", "country": "Philippines", "category": "Canned Food" },
  { "id": "193", "name": "572043201", "origin": "Non-EU", "country": "Unknown", "category": "Food" },
  { "id": "194", "name": "5th Season", "origin": "Non-EU", "country": "USA", "category": "Dried Fruits & Snacks" },
  { "id": "195", "name": "6D Sports Nutrition", "origin": "EU", "country": "Belgium", "category": "Sports Nutrition" },
  { "id": "196", "name": "6PAKNUTRITION", "origin": "EU", "country": "Poland", "category": "Sports Nutrition" },
  { "id": "197", "name": "7 Days", "origin": "EU", "country": "Greece", "category": "Bakery", "parentCompany": "Chipita" },
  { "id": "198", "name": "7 Eleven", "origin": "Non-EU", "country": "Japan/USA", "category": "Retail" },
  { "id": "199", "name": "7 Up", "origin": "Non-EU", "country": "USA", "category": "Beverages", "parentCompany": "PepsiCo" },
  { "id": "200", "name": "9 De Oro", "origin": "Non-EU", "country": "Argentina", "category": "Bakery", "parentCompany": "Molino Cañuelas" },
  { "id": "201", "name": "9 Mile", "origin": "EU", "country": "Germany", "category": "Beverages" },
  { "id": "202", "name": "9 White Deer", "origin": "EU", "country": "Ireland", "category": "Beverages" },
  { "id": "203", "name": "95 Nutrition", "origin": "Non-EU", "country": "USA", "category": "Health & Supplements" },
  { "id": "204", "name": "99 Ranch Market", "origin": "Non-EU", "country": "USA", "category": "Retail" },
  { "id": "205", "name": "9Bar", "origin": "EU", "country": "UK", "category": "Snacks" },
  { "id": "206", "name": "A & W", "origin": "Non-EU", "country": "USA", "category": "Beverages" },
  { "id": "207", "name": "A Bicyclette", "origin": "EU", "country": "France", "category": "Dairy Alternatives", "parentCompany": "Eurial" },
  { "id": "208", "name": "A Bread Affair", "origin": "Non-EU", "country": "Canada", "category": "Bakery" },
  { "id": "209", "name": "8X4", "origin": "EU", "country": "Germany", "category": "Personal Care" },
  { "id": "210", "name": "88 Acres", "origin": "Non-EU", "country": "USA", "category": "Snacks" },
  { "id": "211", "name": "777", "origin": "Non-EU", "country": "India", "category": "Food" },
  { "id": "212", "name": "7th Avenue Pizza", "origin": "Non-EU", "country": "USA", "category": "Frozen Food" },
  { "id": "213", "name": "7th Heaven", "origin": "EU", "country": "Israel", "category": "Confectionery" }
    ];
  
    // TODO: take the first entry of tags