export const eanPrefixes = [
    { range: ["0000000"], country: "Restricted Usage", origin: "Non-EU" },
    { range: ["001", "019"], country: "USA", origin: "Non-EU" },
    { range: ["030", "039"], country: "USA", origin: "Non-EU" },
    { range: ["300", "379"], country: "France", origin: "EU" },
    { range: ["400", "440"], country: "Germany", origin: "EU" },
    { range: ["450", "459"], country: "Japan", origin: "Non-EU" },
    { range: ["460", "469"], country: "Russia", origin: "Non-EU" },
    { range: ["471"], country: "Taiwan", origin: "Non-EU" },
    { range: ["474"], country: "Estonia", origin: "EU" },
    { range: ["475"], country: "Latvia", origin: "EU" },
    { range: ["476"], country: "Azerbaijan", origin: "Non-EU" },
    { range: ["477"], country: "Lithuania", origin: "EU" },
    { range: ["478"], country: "Uzbekistan", origin: "Non-EU" },
    { range: ["500", "509"], country: "United Kingdom", origin: "EU" },
    { range: ["520"], country: "Greece", origin: "EU" },
    { range: ["528"], country: "Lebanon", origin: "Non-EU" },
    { range: ["529"], country: "Cyprus", origin: "EU" },
    { range: ["530"], country: "Albania", origin: "Non-EU" },
    { range: ["535"], country: "Malta", origin: "EU" },
    { range: ["539"], country: "Ireland", origin: "EU" },
    { range: ["540", "549"], country: "Belgium & Luxembourg", origin: "EU" },
    { range: ["560"], country: "Portugal", origin: "EU" },
    { range: ["569"], country: "Iceland", origin: "EU" },
    { range: ["570", "579"], country: "Denmark", origin: "EU" },
    { range: ["590"], country: "Poland", origin: "EU" },
    { range: ["594"], country: "Romania", origin: "EU" },
    { range: ["599"], country: "Hungary", origin: "EU" },
    { range: ["600", "601"], country: "South Africa", origin: "Non-EU" },
    { range: ["690", "699"], country: "China", origin: "Non-EU" },
    { range: ["700", "709"], country: "Norway", origin: "EU" },
    { range: ["729"], country: "Israel", origin: "Non-EU" },
    { range: ["730", "739"], country: "Sweden", origin: "EU" },
    { range: ["750"], country: "Mexico", origin: "Non-EU" },
    { range: ["754", "755"], country: "Canada", origin: "Non-EU" },
    { range: ["760", "769"], country: "Switzerland & Liechtenstein", origin: "EU" },
    { range: ["770"], country: "Colombia", origin: "Non-EU" },
    { range: ["780"], country: "Chile", origin: "Non-EU" },
    { range: ["789", "790"], country: "Brazil", origin: "Non-EU" },
    { range: ["800", "839"], country: "Italy", origin: "EU" },
    { range: ["840", "849"], country: "Spain", origin: "EU" },
    { range: ["858"], country: "Slovakia", origin: "EU" },
    { range: ["859"], country: "Czech Republic", origin: "EU" },
    { range: ["900", "919"], country: "Austria", origin: "EU" },
    { range: ["930", "939"], country: "Australia", origin: "Non-EU" },
    { range: ["940", "949"], country: "New Zealand", origin: "Non-EU" }
];
